RUN-5568 BrowserView ContentNavigation
HadoukenIO/core pull request #973
Opened 2019-09-27 19:55 UTC by aziz512

#### Description of Change
Adds content navigation filtering for BrowserViews through `contentNavigation` option. Usage is identical to the option in Window

Tests:
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d8e665336089855657ecd76

#### Checklist
- [x] PR description included and stakeholders cc'd
- [x] `npm test` passes
- [x] automated tests are [changed or added](https://testing-dashboard.openfin.co/#/app/dashboard)
- [x] PR title starts with the JIRA ticket [pull request process](https://github.com/openfin/Internal-Wiki/wiki/Pull-Request-Process)
- [x] PR release notes describe the change in a way relevant to app-developers
- [x] Link to new tests added
- [x] PR has assigned reviewers

#### Release Notes
Notes: Added BrowserView `contentNavigation` option analogous to Window

@datamadic @pbaize @MichaelMCoates @rdepena

2019-10-04 15:27 UTC, aziz512 commented
Just figured out why it fails to build -- I made some a change to a shape in the js-adapter.
Here's the PR for it https://github.com/HadoukenIO/js-adapter/pull/359 . Once that gets merged, we can get back to this PR.

2019-10-04 18:52 UTC, pbaize commented
Do we need to document these events in the js-adapter?

2019-10-11 15:44 UTC, aziz512 commented
> Do we need to document these events in the js-adapter?

Added docs

2019-10-15 14:55 UTC, pbaize requested changes
Looks good. See the comment on the BrowserView shape. It would also be good not to have formatting changes in this pr

2019-10-15 14:55 UTC, pbaize commented on src/shapes.ts
> +export interface BrowserView {
Let's add this to OfView rather than here. Extending the electron shapes causes headaches

2019-10-18 17:53 UTC, aziz512 commented on src/shapes.ts
> +export interface BrowserView {
That shape was not extending the electron shape, it's just used to shape the options.
I renamed it for clarity in the following commit.

2019-11-04 01:20 UTC, closed without merging